"""Render classified statements as a single readable markdown document.

The digest is the counterpart to `chatmem query`: query answers a question you
already thought to ask, the digest is for the ones you didn't. So its contract
is completeness, not relevance -- every statement stored for the target appears
exactly once, verbatim, under one heading, with the date and the statement id
that `chatmem statements` and `chatmem export` use.

Nothing here calls an LLM. Classification happens once and is stored on the
statement; re-rendering the document is a pure function of the database.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from chatmem import topics
from chatmem.models import Message, Statement

UNCLASSIFIED_KEY = "__unclassified__"


@dataclass(frozen=True)
class DigestMeta:
    """Counts for the document header, gathered by the caller from the store."""

    title: str
    generated_at: str  # ISO-8601
    message_count: int
    session_count: int
    thread_count: int


def _slug(heading: str) -> str:
    """GitHub's anchor slug: lowercase, drop punctuation, spaces to hyphens.

    Matches GitHub verbatim, including that a dropped '&' leaves the spaces on
    either side of it behind -- 'Identity & background' anchors as
    'identity--background', with two hyphens.
    """
    text = heading.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)
    return re.sub(r"\s", "-", text)


def _day(ts: str) -> str:
    return ts[:10]


def _date_label(statement: Statement) -> str:
    start, end = _day(statement.start_ts), _day(statement.end_ts)
    return start if start == end else f"{start} – {end}"


def group_by_topic(statements: list[Statement]) -> dict[str, list[Statement]]:
    """Bucket statements by topic key, in taxonomy order, dropping empty topics.

    Statements with no topic land under UNCLASSIFIED_KEY, ordered last: a
    digest run that partly failed should still render everything it has rather
    than silently omit the rows it could not classify.
    """
    buckets: dict[str, list[Statement]] = {}
    for key in topics.TOPIC_KEYS:
        found = [s for s in statements if s.topic == key]
        if found:
            buckets[key] = found

    known = set(topics.TOPIC_KEYS)
    leftover = [s for s in statements if s.topic is not None and s.topic not in known]
    for s in leftover:
        buckets.setdefault(s.topic or UNCLASSIFIED_KEY, []).append(s)

    untagged = [s for s in statements if s.topic is None]
    if untagged:
        buckets[UNCLASSIFIED_KEY] = untagged

    for bucket in buckets.values():
        bucket.sort(key=lambda s: (s.start_ts, s.id or 0))
    return buckets


def _heading(key: str) -> str:
    return "Unclassified" if key == UNCLASSIFIED_KEY else topics.title_for(key)


def _quote_block(messages: list[Message], indent: str = "  ") -> list[str]:
    lines = []
    for m in messages:
        text = " ".join((m.text or f"[{m.media_type or 'media'}]").split())
        lines.append(f"{indent}> {m.sender}: {text}")
    return lines


def render(
    meta: DigestMeta,
    statements: list[Statement],
    *,
    show_threads: bool = False,
    quotes_by_statement: dict[int, list[Message]] | None = None,
) -> str:
    """Render the whole digest as markdown.

    `show_threads` tags each bullet with the thread it came from; the caller
    turns it on only when the archive has more than one, since a single-thread
    digest would just repeat the same token on every line.
    """
    buckets = group_by_topic(statements)
    out: list[str] = [f"# {meta.title}", ""]
    out.append(
        "<!-- Generated by `chatmem digest`. Edits here are lost on the next run. -->"
    )
    out.append("")

    if statements:
        span_start = min(_day(s.start_ts) for s in statements)
        span_end = max(_day(s.end_ts) for s in statements)
        out.append(
            f"**{len(statements):,} memories** from {meta.message_count:,} messages "
            f"in {meta.session_count:,} sessions across {meta.thread_count} "
            f"thread{'s' if meta.thread_count != 1 else ''}, "
            f"covering {span_start} to {span_end}."
        )
    else:
        out.append("No statements have been extracted yet. Run `chatmem extract` first.")
    out.append("")
    out.append(f"_Generated {_day(meta.generated_at)}._")
    out.append("")

    if not buckets:
        return "\n".join(out) + "\n"

    out.append("## Contents")
    out.append("")
    for key, bucket in buckets.items():
        heading = _heading(key)
        out.append(f"- [{heading}](#{_slug(heading)}) — {len(bucket)}")
    out.append("")

    for key, bucket in buckets.items():
        heading = _heading(key)
        out.append(f"## {heading}")
        out.append("")
        topic = topics.BY_KEY.get(key)
        if topic is not None:
            out.append(f"_{topic.description}_")
            out.append("")
        for s in bucket:
            suffix = f"`#{s.id}`" if s.id is not None else ""
            if show_threads:
                suffix = f"`{s.thread_id}` {suffix}".strip()
            bullet = f"- **{_date_label(s)}** — {s.text}"
            out.append(f"{bullet} {suffix}".rstrip())
            quoted = (quotes_by_statement or {}).get(s.id or -1) or []
            if quoted:
                out.append("")
                out.extend(_quote_block(quoted))
                out.append("")
        out.append("")

    return "\n".join(out).rstrip() + "\n"
